# Generated by Django 5.0.3 on 2024-03-28 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Casa', max_length=20, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras e ter no máximo 50 caracteres.', regex='^[a-zA-Z]{1,50}$')])),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='O CEP deve conter 8 dígitos.', regex='^\\d{8}$')])),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=50)),
                ('address_number', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='O número do endereço deve conter no máximo 7 dígitos.', regex='^\\d{1,7}$')])),
                ('address_complement', models.CharField(blank=True, max_length=20, null=True)),
                ('user_phone', models.CharField(max_length=9)),
                ('user_email', models.EmailField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='O número de telefone deve conter 9 dígitos.', regex='^\\d{9,}$')])),
                ('phone_verified', models.BooleanField(default=False)),
                ('first_name', models.CharField(default='NONAME', max_length=50, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras e ter no máximo 50 caracteres.', regex='^[a-zA-Z]{1,50}$')])),
                ('last_name', models.CharField(default='NONAME', max_length=50, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras e ter no máximo 50 caracteres.', regex='^[a-zA-Z]{1,50}$')])),
                ('email', models.EmailField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
