# Generated by Django 5.0.3 on 2024-03-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveraddress',
            name='user_email',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
    ]
