# Generated by Django 5.0.3 on 2024-03-28 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='title',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
