# Generated by Django 5.0.3 on 2024-03-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='banner',
            field=models.ImageField(default='fallback.png', upload_to='pics/'),
        ),
    ]
