# Generated by Django 5.0.3 on 2024-04-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_email', models.EmailField(default='DEFAULT', max_length=50)),
                ('customer_phone', models.CharField(default='DEFAULT', max_length=50)),
                ('status', models.BooleanField(default=False, max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('products', models.TextField(default=[], max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('qr_code_data', models.CharField(default='DEFAULT', max_length=160)),
                ('qr_code_image', models.ImageField(default='DEFAULT', upload_to='payments/')),
            ],
        ),
    ]
